Newadvancedsettings
Qovery/documentation pull request #140
Opened 2022-06-09 20:22 UTC by AnouckC

2022-06-10 16:23 UTC, alecarrano requested changes
general comment:
- there are files in this PR which should not be here (ruby-version and typescript)
- would it make sense to have a dedicated sub-page for advanced settings instead of adding it to the application page (it's going to increase)?
- it's better to split non-related changes in different PRs (advanced settings vs cluster updates) <-- but it's fine for this time

2022-06-10 16:23 UTC, alecarrano commented on scripts/.ruby-version
> +3.0.4
there's no need to change the ruby version here ;)

2022-06-10 16:23 UTC, alecarrano commented on typescript
> +Script started on Thu Jun  2 15:31:54 2022
why this file in the PR?

2022-06-10 16:23 UTC, alecarrano commented on website/docs/using-qovery/configuration/application.md
> +* **Readiness probes:** to check if the application container is ready to receive requests (as even alive containers can enter phases where they cannot handle incoming traffic). If the check fails, K
"Kubernetes stops routing traffic to the container" -> I'd say rather that Kubernetes sends traffic to the container only if this check passes

2022-06-10 16:23 UTC, alecarrano commented on website/docs/using-qovery/configuration/application.md
> +| string  | Allows you to specify the type of readiness probe you want to launch. <br /> <br/> **HTTP probes** are the most common probe type. You can use them if your application is a HTTP server, o
two quesitons here: where are the port and path specified? I suppose the path is on readiness_probe.http_get.path and the port is the one defined on the console?

2022-06-10 16:23 UTC, alecarrano commented on website/docs/using-qovery/configuration/application.md
> +| string  | Allows you to specify the type of liveness probe you want to launch. <br /> <br/> **HTTP probes** are the most common probe type. You can use them if your application is a HTTP server, or
same comment as for the readiness probe type

2022-06-10 16:23 UTC, alecarrano commented on website/docs/using-qovery/configuration/application.md
> +| boolean | Qovery allows you to set custom domains for your applications through the addition of a CNAME record to your domain's DNS settings. By default, when an application is deployed, Qovery che
can we say that we suggest to set this value to 'false' if they are behind a CDN? cc @deimosfr

2022-06-11 07:52 UTC, deimosfr approved these changes

2022-06-11 07:52 UTC, deimosfr commented on website/docs/using-qovery/configuration/application.md
> +* **Startup probes:** to check if the application has started, and allow additional time for slow-start applications to become ready. If the check fails, the application container is killed and resta
Well...this probe doesn't exists on kubernetes and we're in this section. For DevOps/SRE, it's weird to see it called this way. The Kubernetes word is "initialDelaySeconds". We better find a wording this way without probe inside it. Because it's a parameter of the liveness probe and not a probe in itself.

2022-06-11 07:52 UTC, deimosfr commented on website/docs/using-qovery/configuration/application.md
> +| string  | Allows you to specify the type of readiness probe you want to launch. <br /> <br/> **HTTP probes** are the most common probe type. You can use them if your application is a HTTP server, o
Yes, the path is with readiness_probe.http_get.path and the port is the application port

2022-06-11 07:52 UTC, deimosfr commented on website/docs/using-qovery/configuration/application.md
> +| integer | Allows you to specify a delay, in seconds, between each readiness probe. | `10`          |
I would add interval at the end to make it more clear: "between each readiness probe interval."

2022-06-11 07:52 UTC, deimosfr commented on website/docs/using-qovery/configuration/application.md
> +| integer | Allows you to specify the delay, in seconds, after which the readiness probe times out.| `1`           |
same, interval is missing to me

2022-06-11 07:52 UTC, deimosfr commented on website/docs/using-qovery/configuration/application.md
> +| string  | Allows you to specify the type of liveness probe you want to launch. <br /> <br/> **HTTP probes** are the most common probe type. You can use them if your application is a HTTP server, or
"NONE"` (disables the liveness probe). I would add this is strongly discouraged, making kubernetes unable to know the state of the application.

2022-06-11 07:52 UTC, deimosfr commented on website/docs/using-qovery/configuration/application.md
>  #### liveness_probe.type
Can you please swap liveness and readiness order please. Because in the Kubernetes workflow:
1. The liveness probe is used to see if the app has correctly started
2. The readiness probe is used to know if the traffic can be routed to the started app
I also would like this workflow to figure in the documentation to make it cristal clear for our customers

2022-06-11 07:52 UTC, deimosfr commented on website/docs/using-qovery/configuration/application.md
> +| integer | Allows you to specify a delay, in seconds, between each liveness probe. | `10`          |
same as readiness and interval

2022-06-11 07:52 UTC, deimosfr commented on website/docs/using-qovery/configuration/application.md
> +| integer | Allows you to specify the delay, in seconds, after which the liveness probe times out. | `5`           |
same as readiness and interval

2022-06-11 07:52 UTC, deimosfr commented on website/docs/using-qovery/configuration/application.md
> +| boolean | Qovery allows you to set custom domains for your applications through the addition of a CNAME record to your domain's DNS settings. By default, when an application is deployed, Qovery che
I would rather say something like: if you're using a CDN behind your application, we advise you to disable this feature to save time during your application deployments

2022-06-11 07:52 UTC, deimosfr commented on website/docs/using-qovery/configuration/application.md
>  ####  deployment.hpa_cpu_average_utilization
This one recently changed name. Now it's hpa.cpu.average_utilization_percent

2022-06-14 13:59 UTC, merged