feat: added clone service feature
Qovery/documentation pull request #317
Opened 2023-08-02 11:58 UTC by acarranoqovery

added clone feature service. 

note it has been added as template instead of copying the text around the different services

2023-08-02 13:58 UTC, ctjhoa requested changes

2023-08-02 13:58 UTC, ctjhoa commented on scripts/generate/templates/_partials/_clone_service.md.erb
> +** Importan information **
```suggestion
** Important information **
```

2023-08-02 13:58 UTC, ctjhoa commented on website/docs/using-qovery/configuration/application.md
> +** Importan information **
```suggestion
** Important information **
```

2023-08-02 13:58 UTC, ctjhoa commented on website/docs/using-qovery/configuration/cronjob.md
> +** Importan information **
```suggestion
** Important information **
```

2023-08-02 13:58 UTC, ctjhoa commented on website/docs/using-qovery/configuration/database.md
> +** Importan information **
```suggestion
** Important information **
```

2023-08-02 13:58 UTC, ctjhoa commented on website/docs/using-qovery/configuration/lifecycle-job.md
> +** Importan information **
```suggestion
** Important information **
```

2023-08-02 14:12 UTC, acarranoqovery commented on scripts/generate/templates/_partials/_clone_service.md.erb
> +** Importan information **
fixed

2023-08-03 05:52 UTC, ctjhoa approved these changes

2023-08-03 07:14 UTC, merged