Add helm
Qovery/documentation pull request #351
Opened 2023-12-04 15:27 UTC by jul-dan

2023-12-04 18:28 UTC, acarranoqovery requested changes

2023-12-04 18:28 UTC, acarranoqovery commented on website/sidebars.js.erb
> +            <%= metadata.links.fetch_id("docs.using-qovery.integration.helm-repository").to_json %>,
on top of these 2, we are missing one line on the docs.using-qovery.configuration.organization.helm-repository (right now the page helm-repository doesn't appear on the sidebar)

2023-12-04 18:28 UTC, acarranoqovery commented on website/static/img/configuration/organization/helm_repository_1.png
this image is too big and take too much space on the rendered page. maybe you should focus more on the interesting section?

2023-12-04 18:28 UTC, acarranoqovery commented on website/docs/using-qovery/configuration/organization/helm-repository.md.erb
> +- Kind: OCI or HTTPS
- HTTP: for standard helm repository
- OCI: for OCI-based registries

2023-12-04 18:28 UTC, acarranoqovery commented on website/docs/using-qovery/configuration/organization/helm-repository.md.erb
> +- Credentials: these depends on the chosen repository type. If a helm repository is public, you don't need to fill this part.
these depend

2023-12-04 18:28 UTC, acarranoqovery commented on website/docs/using-qovery/configuration/organization/helm-repository.md.erb
> +Before deleting it, make sure that there is no helm within your organization using an image stored in this repository.
make sure there is no helm service within your organization using a helm chart stored in this repository

2023-12-05 12:03 UTC, acarranoqovery commented on website/docs/using-qovery/configuration/helm.md.erb
> +The list of Git repositories available during the setup is strictly tied to the permissions of your git account (by default Qovery can access all your repositories). If you want to restrict the Qover
to complete my comment: indeed there's no official way today to restrict the list of git repository we have access and we need to implement a proper SSO mechanism to change this (we can discuss it offline since it's probably not 100% clear from my message)

2023-12-05 12:15 UTC, acarranoqovery commented on website/docs/using-qovery/configuration/helm.md.erb
> +- Git Repository: Select the git provider hosting your code (it can be hosted on GitHub, GitLab or Bitbucket).
hosting your value override (it can be the same as the one hosting the helm chart)

2023-12-05 12:18 UTC, acarranoqovery commented on website/docs/using-qovery/configuration/helm.md.erb
> +  - Select `File` to use the `--set-file` flag to set individual values from a file when the value itself is too long for the command line or is dynamically generated
`File` not supported

2023-12-05 12:21 UTC, acarranoqovery commented on website/docs/using-qovery/configuration/helm.md.erb
> +- Namespace (only if Allow cluster-wide resources was enabled): this is the kubernetes namespace in your helm chart
"kubernetes namespace used by your helm chart to deploy the pods behind the chosen service"

2023-12-05 12:21 UTC, acarranoqovery commented on website/docs/using-qovery/configuration/helm.md.erb
> +- Service port: this is the port exposed internally by your service for the other services
remove the "for the other services".

2023-12-05 12:22 UTC, acarranoqovery commented on website/docs/using-qovery/configuration/helm.md.erb
> +- Port Name: it is the name assigned to the port. When multiple ports are exposed publicly, its value is used to route the traffic to the right port based on the called subdomain (which will contain
this will change in the future but let's keep it like this for now

2023-12-05 12:24 UTC, acarranoqovery commented on website/docs/using-qovery/configuration/helm.md.erb
> +By default ports are accessible only from inside your namespace(s). You can also expose them publicly, making them accessible over the public network via a dedicated public domain that will be assign
to be rephrased? you can only expose publicly services so it's weird to have "also expose them publicly"

2023-12-05 12:26 UTC, acarranoqovery commented on website/docs/using-qovery/configuration/helm.md.erb
> +#### Arguments
to discuss: we often repeat in the settings the text we wrote from the creation flow . maybe there's a better way to build the doc 🤷

2023-12-05 12:27 UTC, acarranoqovery commented on website/docs/using-qovery/configuration/helm.md.erb
> +If you want to override it with a raw yaml you will have to click on `Create override`. A new editor modal will be opened, to let you write your yaml override. The default values.yaml content will be
note: there's also the override via paramaters/arguments

2023-12-05 16:18 UTC, jul-dan commented on website/static/img/configuration/organization/helm_repository_1.png
I did this to avoid pixeled picture

2023-12-05 16:41 UTC, jul-dan commented on website/docs/using-qovery/configuration/helm.md.erb
> +#### Arguments
Added in our kanban

2023-12-06 08:26 UTC, acarranoqovery approved these changes
one small update on the domains and we are good

2023-12-06 08:26 UTC, acarranoqovery commented on scripts/generate/templates/_partials/_configure_domains.md.erb
> +Example: `p80-zdf72de72-z709e1a88-gtw.za8ad0657.bool.sh`
I'd add that for helm services the domain is <service_name>-p<portname>-z...  so it would be grafana-p80-zdf72de72-z709e1a88-gtw.za8ad0657.bool.sh

2023-12-19 14:21 UTC, acarranoqovery approved these changes

2023-12-19 14:24 UTC, merged