preview env and cluster
Qovery/documentation pull request #78
Opened 2021-12-01 14:07 UTC by Albanetonnellier

Create a stop cluster page + updated stop cluster for cloud provider + update preview environment and create page environment

2021-12-06 11:10 UTC, evoxmusic requested changes

2021-12-06 11:10 UTC, evoxmusic commented on website/docs/using-qovery/configuration.md
> +<Jump to="/docs/using-qovery/configuration/preview-env/">Preview env</Jump>
Please use `preview environment` and not `preview env` for the URL and the naming - stay consistent in the naming.

2021-12-06 11:10 UTC, evoxmusic commented on website/docs/using-qovery/configuration.md
> +<Jump to="/docs/using-qovery/configuration/stop-cluster/">Stop cluster</Jump>
why a new page for stopping the cluster? It should be on the cluster page. Not on a dedicated page.

2021-12-06 11:10 UTC, evoxmusic commented on website/docs/using-qovery/configuration/environment.md
> +Refer to the [Preview Environment][docs.using-qovery.configuration.preview-env] documentation to know more.
why use a dedicated page for the preview environment? It is an Environment feature. It should not be in "configuration", but in a sub section of "Environment"

2021-12-06 11:10 UTC, evoxmusic commented on website/docs/using-qovery/configuration/environment.md
> +[docs.using-qovery.configuration.preview-env]: /docs/using-qovery/configuration/preview-env/
same

2021-12-06 11:10 UTC, evoxmusic commented on website/docs/using-qovery/configuration/environment.md.erb
> +Refer to the [Preview Environment][docs.using-qovery.configuration.preview-env] documentation to know more.
same

2021-12-06 11:15 UTC, Albanetonnellier commented on website/docs/using-qovery/configuration.md
> +<Jump to="/docs/using-qovery/configuration/preview-env/">Preview env</Jump>
I used preview environment at the beginning but it created a conflict with the file environment and couldn't generate the md that's why I changed it, is there a way not to create a conflict?

2022-01-10 10:54 UTC, evoxmusic commented
@Albanetonnellier can you apply my changes/suggestions?

2022-01-11 14:58 UTC, Albanetonnellier commented
@evoxmusic this pr is no longer needed, Florian made a new page with the new cluster flow

2022-01-20 10:59 UTC, closed without merging