adding ssh_key is now possible for cloning sub
Qovery/documentation pull request #85
Opened 2022-01-07 08:56 UTC by Albanetonnellier

adding ssh_key is now possible for cloning submodules

2022-01-10 10:52 UTC, evoxmusic requested changes

2022-01-10 10:52 UTC, evoxmusic commented on website/docs/using-qovery/configuration/application.md
> +  ```bash
@Albanetonnellier - can you remove the space/tab?

2022-01-10 10:52 UTC, evoxmusic commented on website/docs/using-qovery/configuration/application.md
> +  GIT_SSH_KEY_xxx
same here

2022-01-10 10:52 UTC, evoxmusic commented on website/docs/using-qovery/configuration/application.md
> +  GIT_SSH_KEY_xxx
@Albanetonnellier can you explain what is the `_xxx`. What do you expect? Can we have multiple SSH private keys and passphrases? How does it work?

2022-01-10 10:52 UTC, evoxmusic commented on website/docs/using-qovery/configuration/application.md.erb
> +  ```bash
same here

2022-01-10 10:52 UTC, evoxmusic commented on website/docs/using-qovery/configuration/application.md.erb
> +  GIT_SSH_KEY_xxx
same here

2022-01-11 15:24 UTC, Albanetonnellier commented on website/docs/using-qovery/configuration/application.md
> +  GIT_SSH_KEY_xxx
the _xxx is to tell that you can put whatever name you want at the end for example GIT_SSH_KEY_PRODUCTION
we will take the ssh keys in the env starting with GIT_SSH_KEY
and we can have multiples ssh private keys.

2022-10-25 13:31 UTC, closed without merging

2022-10-25 13:31 UTC, alecarrano commented
closing since submodules are already documented